version: '2'
services:
  category-classifier-db:
    build: .
    #comment
    volumes:
      - ./etc:/usr/local/etc/couchdb/local.d
      - ./lib:/usr/local/var/lib/couchdb
    ports:
      - "3306:5984"
